import { PrebuiltWorkflowTemplate } from "./types";

export const PREBUILT_WORKFLOWS: Record<string, PrebuiltWorkflowTemplate> = {
  "product-photo-enhancer": {
    intentId: "product-photo-enhancer",
    nameAr: "تحسين صورة منتج احترافية",
    nameEn: "Professional Product Photo Enhancer",
    descAr: "سلسلة متكاملة: إزالة الخلفية + تنظيف التفاصيل + ترقية الدقة بدقة 4K",
    descEn: "Full pipeline: RMBG-2.0 Background Removal -> Denoise -> Real-ESRGAN 4K Upscale",
    mediaType: "image",
    estimatedDurationMs: 4500,
    steps: [
      {
        id: "step-1-bg-removal",
        name: "إزالة الخلفية (RMBG-2.0)",
        taskType: "background-removal",
        pluginId: "plugin-image-enhancement",
        actionName: "remove-background",
        outputField: "outputImageBase64OrUrl",
      },
      {
        id: "step-2-denoise",
        name: "تنظيف النويز والحواف (SCUNet)",
        taskType: "noise-reduction",
        pluginId: "plugin-image-enhancement",
        actionName: "denoise",
        dependsOn: ["step-1-bg-removal"],
        inputPipeFromStepId: "step-1-bg-removal",
        outputField: "outputImageBase64OrUrl",
      },
      {
        id: "step-3-upscale",
        name: "ترقية الدقة x4 (Real-ESRGAN)",
        taskType: "enhance-media",
        pluginId: "plugin-image-enhancement",
        actionName: "upscale",
        dependsOn: ["step-2-denoise"],
        inputPipeFromStepId: "step-2-denoise",
        payloadTemplate: { upscaleFactor: 4 },
        outputField: "outputImageBase64OrUrl",
      },
    ],
  },

  "podcast-cleaner": {
    intentId: "podcast-cleaner",
    nameAr: "تنظيف ومعالجة البودكاست",
    nameEn: "Podcast Audio Cleaner & Master",
    descAr: "سلسلة تنظيف الصوت: إزالة ضوضاء الغرفة + عزل الكلام النقية + المكس النهائي",
    descEn: "Full audio pipeline: DeepFilterNet Denoise -> Demucs Vocal Isolation -> Composite Audio Master",
    mediaType: "audio",
    estimatedDurationMs: 6000,
    steps: [
      {
        id: "step-1-noise-reduction",
        name: "تنقية الضوضاء والصدى (DeepFilterNet)",
        taskType: "noise-reduction",
        pluginId: "plugin-audio-enhancement",
        actionName: "denoise",
        payloadTemplate: { denoiseIntensity: 0.85 },
        outputField: "enhancedAudioUrlOrBase64",
      },
      {
        id: "step-2-vocal-isolation",
        name: "عزل صوت المتحدث (Demucs v4)",
        taskType: "vocal-isolation",
        pluginId: "plugin-audio-enhancement",
        actionName: "separate",
        dependsOn: ["step-1-noise-reduction"],
        inputPipeFromStepId: "step-1-noise-reduction",
        payloadTemplate: { separationMode: "extract-vocals" },
        outputField: "enhancedAudioUrlOrBase64",
      },
      {
        id: "step-3-audio-master",
        name: "المكس والماسترينغ الصوتي النهائي",
        taskType: "enhance-media",
        pluginId: "plugin-audio-enhancement",
        actionName: "audio-enhance-composite",
        dependsOn: ["step-2-vocal-isolation"],
        inputPipeFromStepId: "step-2-vocal-isolation",
        outputField: "enhancedAudioUrlOrBase64",
      },
    ],
  },

  "short-video-enhancer": {
    intentId: "short-video-enhancer",
    nameAr: "تحسين وإنشاء فيديو قصير احترافي",
    nameEn: "Short Video Master Pipeline",
    descAr: "تنقية نويز الفيديو + مضاعفة سلاسة الإطارات 60fps + ترقية الدقة 4K + توازن HDR",
    descEn: "Video Denoise -> RIFE 60fps Interpolation -> 4K Upscale -> Auto Color HDR",
    mediaType: "video",
    estimatedDurationMs: 12000,
    steps: [
      {
        id: "step-1-vid-denoise",
        name: "تنقية تشويش الفيديو (FastDVDnet)",
        taskType: "noise-reduction",
        pluginId: "plugin-video-enhancement",
        actionName: "video-denoise",
        outputField: "outputVideoBase64OrUrl",
      },
      {
        id: "step-2-interpolation",
        name: "مضاعفة سلاسة الحركة 60fps (RIFE)",
        taskType: "enhance-media",
        pluginId: "plugin-video-enhancement",
        actionName: "frame-interpolation",
        dependsOn: ["step-1-vid-denoise"],
        inputPipeFromStepId: "step-1-vid-denoise",
        payloadTemplate: { targetFps: 60 },
        outputField: "outputVideoBase64OrUrl",
      },
      {
        id: "step-3-vid-upscale",
        name: "ترقية الدقة إلى 4K (Real-ESRGAN Video)",
        taskType: "enhance-media",
        pluginId: "plugin-video-enhancement",
        actionName: "video-upscale",
        dependsOn: ["step-2-interpolation"],
        inputPipeFromStepId: "step-2-interpolation",
        payloadTemplate: { upscaleFactor: 4 },
        outputField: "outputVideoBase64OrUrl",
      },
      {
        id: "step-4-auto-color",
        name: "تحسين الألوان وتباين HDR",
        taskType: "enhance-media",
        pluginId: "plugin-video-enhancement",
        actionName: "auto-color-enhance",
        dependsOn: ["step-3-vid-upscale"],
        inputPipeFromStepId: "step-3-vid-upscale",
        outputField: "outputVideoBase64OrUrl",
      },
    ],
  },

  "bg-remove-upscale": {
    intentId: "bg-remove-upscale",
    nameAr: "إزالة الخلفية وترقية الجودة",
    nameEn: "Background Removal & Super Resolution",
    descAr: "عزل العناصر من الصور ثم ترقية الدقة والوضوح",
    descEn: "Extract foreground and upscale image resolution",
    mediaType: "image",
    estimatedDurationMs: 3500,
    steps: [
      {
        id: "step-1-bg-removal",
        name: "إزالة الخلفية",
        taskType: "background-removal",
        pluginId: "plugin-image-enhancement",
        actionName: "remove-background",
        outputField: "outputImageBase64OrUrl",
      },
      {
        id: "step-2-upscale",
        name: "ترقية الوضوح والدقة",
        taskType: "enhance-media",
        pluginId: "plugin-image-enhancement",
        actionName: "upscale",
        dependsOn: ["step-1-bg-removal"],
        inputPipeFromStepId: "step-1-bg-removal",
        payloadTemplate: { upscaleFactor: 2 },
        outputField: "outputImageBase64OrUrl",
      },
    ],
  },

  "auto-captioning": {
    intentId: "auto-captioning",
    nameAr: "إنشاء وتوليد كابشن تلقائي",
    nameEn: "Auto Speech Captioning & Translation",
    descAr: "تفريغ الصوت ذكياً بواسطة Groq Whisper ثم ترجمة النصوص تلقائياً",
    descEn: "Groq Whisper STT speech transcription -> Translation pipeline",
    mediaType: "audio",
    estimatedDurationMs: 4000,
    steps: [
      {
        id: "step-1-stt",
        name: "تفريغ الصوت إلى نص (Groq Whisper)",
        taskType: "speech-to-text",
        pluginId: "plugin-audio-enhancement",
        actionName: "transcribe",
        outputField: "transcriptionText",
      },
      {
        id: "step-2-translation",
        name: "ترجمة وصياغة الكابشن",
        taskType: "translation",
        pluginId: "plugin-audio-enhancement",
        actionName: "translate-captions",
        dependsOn: ["step-1-stt"],
        inputPipeFromStepId: "step-1-stt",
        outputField: "translatedCaptions",
      },
    ],
  },
};
