import { PrebuiltWorkflowTemplate } from "./types";

export const PREBUILT_WORKFLOWS: Record<string, PrebuiltWorkflowTemplate> = {
  "product-photo-enhancer": {
    intentId: "product-photo-enhancer",
    nameAr: "تحسين صورة منتج احترافية",
    nameEn: "Professional Product Photo Enhancer",
    descAr: "سلسلة متكاملة: إزالة الخلفية + تنظيف التفاصيل + تحسين التباين والإضاءة",
    descEn: "Full pipeline: Background Removal -> Denoise -> Adaptive Contrast & HDR Enhance",
    mediaType: "image",
    estimatedDurationMs: 3500,
    steps: [
      {
        id: "step-1-bg-removal",
        name: "إزالة الخلفية",
        taskType: "background-removal",
        pluginId: "plugin-image-enhancement",
        actionName: "remove-background",
        outputField: "outputImageBase64OrUrl",
      },
      {
        id: "step-2-denoise",
        name: "تنظيف النويز والحواف",
        taskType: "noise-reduction",
        pluginId: "plugin-image-enhancement",
        actionName: "denoise",
        dependsOn: ["step-1-bg-removal"],
        inputPipeFromStepId: "step-1-bg-removal",
        outputField: "outputImageBase64OrUrl",
      },
      {
        id: "step-3-enhance",
        name: "تحسين التباين والتفاصيل",
        taskType: "enhance-media",
        pluginId: "plugin-image-enhancement",
        actionName: "enhance",
        dependsOn: ["step-2-denoise"],
        inputPipeFromStepId: "step-2-denoise",
        outputField: "outputImageBase64OrUrl",
      },
    ],
  },

  "podcast-cleaner": {
    intentId: "podcast-cleaner",
    nameAr: "تنظيف ومعالجة البودكاست",
    nameEn: "Podcast Audio Cleaner & Master",
    descAr: "سلسلة تنظيف الصوت: إزالة ضوضاء الغرفة + عزل الكلام النقية + المكس النهائي",
    descEn: "Full audio pipeline: DeepFilterNet Denoise -> Demucs Vocal Isolation -> Composite Audio Master",
    mediaType: "audio",
    estimatedDurationMs: 6000,
    steps: [
      {
        id: "step-1-noise-reduction",
        name: "تنقية الضوضاء والصدى (DeepFilterNet)",
        taskType: "noise-reduction",
        pluginId: "plugin-audio-enhancement",
        actionName: "denoise",
        payloadTemplate: { denoiseIntensity: 0.85 },
        outputField: "enhancedAudioUrlOrBase64",
      },
      {
        id: "step-2-vocal-isolation",
        name: "عزل صوت المتحدث (Demucs v4)",
        taskType: "vocal-isolation",
        pluginId: "plugin-audio-enhancement",
        actionName: "separate",
        dependsOn: ["step-1-noise-reduction"],
        inputPipeFromStepId: "step-1-noise-reduction",
        payloadTemplate: { separationMode: "extract-vocals" },
        outputField: "enhancedAudioUrlOrBase64",
      },
      {
        id: "step-3-audio-master",
        name: "المكس والماسترينغ الصوتي النهائي",
        taskType: "enhance-media",
        pluginId: "plugin-audio-enhancement",
        actionName: "audio-enhance-composite",
        dependsOn: ["step-2-vocal-isolation"],
        inputPipeFromStepId: "step-2-vocal-isolation",
        outputField: "enhancedAudioUrlOrBase64",
      },
    ],
  },

  "short-video-enhancer": {
    intentId: "short-video-enhancer",
    nameAr: "تحسين ومعالجة الفيديو الاحترافي",
    nameEn: "Pro Video Enhancement Pipeline",
    descAr: "تنقية نويز الفيديو + توازن تباين CLAHE وألوان HDR وتوضيح التفاصيل",
    descEn: "Adaptive CLAHE Contrast, Bilateral Denoise & Micro-Detail Sharpening",
    mediaType: "video",
    estimatedDurationMs: 6000,
    steps: [
      {
        id: "step-1-vid-enhance",
        name: "تحسين الفيديو وموازنة التباين",
        taskType: "enhance-media",
        pluginId: "plugin-video-enhancement",
        actionName: "composite-video-enhance",
        payloadTemplate: { denoiseIntensity: 0.65, sharpnessIntensity: 0.5, claheClipLimit: 2.0, colorVibrance: 0.35 },
        outputField: "outputVideoBase64OrUrl",
      },
    ],
  },

  "bg-remove-enhance": {
    intentId: "bg-remove-enhance",
    nameAr: "إزالة الخلفية وتحسين الجودة",
    nameEn: "Background Removal & AI Enhancement",
    descAr: "عزل العناصر من الصور ثم تحسين الوضوح والتباين",
    descEn: "Extract foreground and enhance image clarity",
    mediaType: "image",
    estimatedDurationMs: 2500,
    steps: [
      {
        id: "step-1-bg-removal",
        name: "إزالة الخلفية",
        taskType: "background-removal",
        pluginId: "plugin-image-enhancement",
        actionName: "remove-background",
        outputField: "outputImageBase64OrUrl",
      },
      {
        id: "step-2-enhance",
        name: "تحسين الوضوح والألوان",
        taskType: "enhance-media",
        pluginId: "plugin-image-enhancement",
        actionName: "enhance",
        dependsOn: ["step-1-bg-removal"],
        inputPipeFromStepId: "step-1-bg-removal",
        outputField: "outputImageBase64OrUrl",
      },
    ],
  },

  "auto-captioning": {
    intentId: "auto-captioning",
    nameAr: "إنشاء وتوليد كابشن تلقائي",
    nameEn: "Auto Speech Captioning & Translation",
    descAr: "تفريغ الصوت ذكياً بواسطة Groq Whisper ثم ترجمة النصوص تلقائياً",
    descEn: "Groq Whisper STT speech transcription -> Translation pipeline",
    mediaType: "audio",
    estimatedDurationMs: 4000,
    steps: [
      {
        id: "step-1-stt",
        name: "تفريغ الصوت إلى نص (Groq Whisper)",
        taskType: "speech-to-text",
        pluginId: "plugin-audio-enhancement",
        actionName: "transcribe",
        outputField: "transcriptionText",
      },
      {
        id: "step-2-translation",
        name: "ترجمة وصياغة الكابشن",
        taskType: "translation",
        pluginId: "plugin-audio-enhancement",
        actionName: "translate-captions",
        dependsOn: ["step-1-stt"],
        inputPipeFromStepId: "step-1-stt",
        outputField: "translatedCaptions",
      },
    ],
  },
};
